#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := Button.cpp ButtonHandeler.cpp IRSendController.cpp KeyboardControl.cpp MainController.cpp receiver.cpp StructData.cpp WindowController.cpp

# header files in this project
HEADERS := Button.hpp ButtonHandeler.hpp IRSendController.hpp KeyboardControl.hpp MainController.hpp receiver.hpp WindowController.hpp PlayerInformation.hpp PinPWMD2.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due